// <auto-generated />
namespace AvDB_lab4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Attachment_Relationship_Corrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Attachment_Relationship_Corrections));
        
        string IMigrationMetadata.Id
        {
            get { return "201412090026321_Attachment_Relationship_Corrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
