// <auto-generated />
namespace AvDB_lab4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addattachments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addattachments));
        
        string IMigrationMetadata.Id
        {
            get { return "201412082220490_Add attachments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
